n1 = int(input('digite um numero: '))
print('=================')
print(n1, 'X 1 = {}'.format(n1 * 1))
print(n1, 'X 2 = {}'.format(n1 * 2))
print(n1, 'X 3 = {}'.format(n1 * 3))
print(n1, 'X 4 = {}'.format(n1 * 4))
print(n1, 'X 5 = {}'.format(n1 * 5))
print(n1, 'X 6 = {}'.format(n1 * 6))
print(n1, 'X 7 = {}'.format(n1 * 7))
print(n1, 'X 8 = {}'.format(n1 * 8))
print(n1, 'X 9 = {}'.format(n1 * 9))
print(n1, 'X10 = {}'.format(n1 * 2 * 5))
print('=================')