f = str(input('digite uma frase comunista: ')).strip().lower()
frt = f.replace('ã', 'a')
frc = frt.replace('â', 'a')
fra = frc.replace('á', 'a')
frcr = fra.replace('à', 'a')
print('a frase possui {} letras A'.format(frcr.count('a')))
print('a priemira vez que essa letra aparece é no caractere {}'.format(frcr.find('a')+1))
print('a última vez que essa letra aparece é no caractere {}'.format(frcr.rfind('a')+1))
print(len(frcr))
