bra = ('Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico PR', 'Atletico MG', 'Fortaleza', 'São Paulo', 'América MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atletico GO', 'Avaí', 'Juventude')
print('=-' * 55)
print(f'O cinco primeiros colocados são: {bra[:5]}')
print('=-' * 55)
print(f'Os últimos quatro: {bra[-4:]}')
print('=-' * 135)
print(f'Os times em {sorted(bra)}')
print('=-' * 135)
print(f'Já a colocação do Bragantino é: {bra.index("Bragantino")}')
print('=-' * 20)